services:
  db:
    image: postgres:16
    container_name: taskmanager_db
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: .
    container_name: taskmanager_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskdb
      SPRING_DATASOURCE_USERNAME: taskuser
      SPRING_DATASOURCE_PASSWORD: taskpass
      APP_JWT_SECRET: change-this-to-a-long-random-secret-64+chars
      SERVER_PORT: "8080"
    ports:
      - "8080:8080"
    # optional: small memory hints
    # environment:
    #   JAVA_OPTS: "-Xms256m -Xmx512m"

volumes:
  pgdata:
