server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: taskmanager-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update   # ✅ TEMPORARY: auto-create missing columns
    show-sql: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expires-minutes: 120
